import React,{useEffect,useMemo,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Mic,MicOff,Volume2,RotateCcw,Trophy,BookOpen,ChevronRight,CheckCircle2,XCircle,Keyboard,Brain,Flame}from'lucide-react';
import { WORDS } from './data/words';
import type { Word, Level } from './data/words';
import './styles.css';

declare global{interface Window{SpeechRecognition?:any;webkitSpeechRecognition?:any}}
type Stats={seen:string[];correct:number;attempts:number;streak:number;best:number};
const EMPTY:Stats={seen:[],correct:0,attempts:0,streak:0,best:0};
const normalize=(s:string)=>s.toLowerCase().replace(/[^a-z\s]/g,' ').replace(/\s+/g,' ').trim();
function scoreAnswer(answer:string,w:Word){const a=normalize(answer), target=normalize(w.word);if(!a)return{ok:false,msg:'Say or type an answer first.'};const exact=new RegExp(`\\b${target}\\b`,'i').test(a);const semantic=w.synonyms.some(s=>a.includes(normalize(s)));if(exact)return{ok:true,msg:`Great use of “${w.word}”. You used the target word correctly.`};if(semantic)return{ok:true,msg:`Good understanding. You used a close idea; next time, try using “${w.word}” itself.`};return{ok:false,msg:`Not quite. Try using “${w.word}” in a sentence that matches its meaning.`}}
function App(){
 const[active,setActive]=useState(false),[level,setLevel]=useState<Level>('Beginner'),[idx,setIdx]=useState(0),[answer,setAnswer]=useState(''),[listening,setListening]=useState(false),[feedback,setFeedback]=useState<{ok:boolean;msg:string}|null>(null),[stats,setStats]=useState<Stats>(()=>{try{return JSON.parse(localStorage.getItem('lexivoice-stats')||'null')||EMPTY}catch{return EMPTY}});const rec=useRef<any>(null);
 const pool=useMemo(()=>WORDS.filter(w=>w.level===level),[level]);const word=pool[idx%pool.length];const supported=!!(window.SpeechRecognition||window.webkitSpeechRecognition);
 useEffect(()=>localStorage.setItem('lexivoice-stats',JSON.stringify(stats)),[stats]);
 useEffect(()=>{if(!active)return;setAnswer('');setFeedback(null);speak(`Your word is ${word.word}. ${word.definition}. Example: ${word.example}. ${word.prompt}`)},[active,word.word]);
 function speak(t:string){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.92;u.pitch=1;u.lang='en-US';speechSynthesis.speak(u)}
 function listen(){if(!supported)return; if(listening){rec.current?.stop();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();rec.current=r;r.lang='en-US';r.interimResults=true;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;setAnswer(t.trim())};r.start()}
 function submit(){const result=scoreAnswer(answer,word);setFeedback(result);setStats(s=>{const streak=result.ok?s.streak+1:0;return{seen:Array.from(new Set([...s.seen,word.word])),attempts:s.attempts+1,correct:s.correct+(result.ok?1:0),streak,best:Math.max(s.best,streak)}});speak(result.msg)}
 function next(){setIdx(i=>(i+1)%pool.length);setAnswer('');setFeedback(null)}
 function changeLevel(l:Level){setLevel(l);setIdx(0);setFeedback(null);setAnswer('')}
 function reset(){setStats(EMPTY);localStorage.removeItem('lexivoice-stats')}
 if(!active)return <main className="landing"><div className="glow g1"/><div className="glow g2"/><nav><div className="brand"><span className="logo"><Volume2/></span>LexiVoice</div><span className="pill">Voice vocabulary coach</span></nav><section className="hero"><div className="eyebrow"><Brain size={16}/> Speak. Learn. Remember.</div><h1>Build a stronger vocabulary<br/><em>one conversation at a time.</em></h1><p>LexiVoice teaches useful English words, listens to you use them, and gives instant feedback—all through natural voice practice.</p><button className="primary big" onClick={()=>setActive(true)}><Mic/> Start learning <ChevronRight/></button><div className="features"><span><CheckCircle2/> Voice practice</span><span><CheckCircle2/> Instant feedback</span><span><CheckCircle2/> Progress saved</span></div></section></main>;
 return <main className="app"><header><div className="brand"><span className="logo"><Volume2/></span>LexiVoice</div><div className="headerStats"><span><Flame size={17}/><b>{stats.streak}</b> streak</span><span><Trophy size={17}/><b>{stats.correct}</b> correct</span></div></header><div className="shell"><aside><p className="label">DIFFICULTY</p>{(['Beginner','Intermediate','Advanced']as Level[]).map(l=><button key={l} className={level===l?'level active':'level'} onClick={()=>changeLevel(l)}>{l}</button>)}<div className="progressBox"><BookOpen/><div><b>{stats.seen.length} words learned</b><small>{stats.attempts?Math.round(stats.correct/stats.attempts*100):0}% accuracy · best streak {stats.best}</small></div></div><button className="reset" onClick={reset}><RotateCcw/> Reset progress</button></aside><section className="lesson"><div className="lessonTop"><span className="pill">{level}</span><span>Word {(idx%pool.length)+1} of {pool.length}</span></div><article className="card"><div className="wordRow"><div><p className="label">TODAY'S WORD</p><h2>{word.word}</h2></div><button className="iconBtn" aria-label="Hear word" onClick={()=>speak(`${word.word}. ${word.word}.`)}><Volume2/></button></div><p className="definition">{word.definition}</p><div className="example"><span>Example</span>“{word.example}”</div><div className="synonyms"><span>Similar:</span>{word.synonyms.map(x=><i key={x}>{x}</i>)}</div></article><article className="practice"><p className="label">YOUR TURN</p><h3>{word.prompt}</h3><p>Speak naturally. Your answer should show that you understand the word.</p><div className="answerBox"><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={supported?'Tap the microphone and speak, or type your answer…':'Voice recognition is unavailable in this browser. Type your answer here…'}/><button className={listening?'mic live':'mic'} onClick={listen} disabled={!supported}>{listening?<MicOff/>:<Mic/>}</button></div>{listening&&<div className="listening"><span/><span/><span/> Listening…</div>}{!supported&&<div className="browserNote"><Keyboard size={16}/> Text mode is active. For voice recognition, use a supported Chromium browser.</div>}<div className="actions"><button className="secondary" onClick={()=>speak(`${word.word}. ${word.definition}. ${word.example}`)}><Volume2/> Hear again</button><button className="primary" onClick={submit}>Check answer <ChevronRight/></button></div>{feedback&&<div className={feedback.ok?'feedback good':'feedback bad'}>{feedback.ok?<CheckCircle2/>:<XCircle/>}<div><b>{feedback.ok?'Nice work!':'Try once more'}</b><p>{feedback.msg}</p></div>{feedback.ok&&<button onClick={next}>Next word <ChevronRight/></button>}</div>}</article></section></div></main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
